---

- name: Create jenkins scripts dir
  file:
    path:  "{{ jenkins_helper_scripts_dir }}"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode:  0755
    state: directory

- name: Copy jenkins config helper scripts
  copy:
    src:   "{{ item }}"
    dest:  "{{ jenkins_helper_scripts_dir }}"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode:  0644
  with_items:
    - cli_helper.groovy
    - grant_global_matrix_permissions.groovy

- name: Extract jenkins-cli.jar
  shell: >
      jar -xf {{ jenkins_war_path }} WEB-INF/jenkins-cli.jar &&
          mv WEB-INF/jenkins-cli.jar ./ &&
          rm -rf WEB-INF &&
          chown {{ jenkins_user }}: jenkins-cli.jar
  args:
    chdir:   "{{ jenkins_helper_scripts_dir }}"
    creates: "{{ jenkins_helper_scripts_dir }}/jenkins-cli.jar"

- name: Disable CLI 'remoting' option for security
  copy:
    src: jenkins.CLI.xml
    dest: "{{ jenkins_home }}"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: 0644
  notify: Restart jenkins
